[profile.default]
out = "build/out"
cache_path = "build/cache"
broadcast = "build/broadcast"

solc_version = "0.8.30"
remappings = [
  "@/=src/",
  "@script/=script/",
  "@test/=test/",
  "@forge-std/=lib/forge-std/src/",
  "@oz/=lib/openzeppelin-contracts/contracts/",
]
auto_detect_remappings = false

fs_permissions = [
  # Allow read access to the broadcast file for ProposeValidators script to extract
  # the validator info and when validators can be accepted (executableAt timestamp).
  { access = "read", path = "build/broadcast/ProposeValidators.s.sol" },
]
